import { ArrowLeft, FileSignature } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { ContractStatusBadge, SignatureStatusBadge } from '../../components/customers/contracts/ContractBadges'
import { initialCustomers } from '../../data/customerMockData'
import { contractRepository } from '../../repositories/contractRepository'
import { quotationRepository } from '../../repositories/quotationRepository'
import { serviceRequestRepository } from '../../repositories/serviceRequestRepository'
import { getEffectiveContractStatus } from '../../utils/contractStatus'
import { formatCurrency } from '../../utils/formatCurrency'

export function ContractDetailsPlaceholder() { const { contractId } = useParams(); const contract = contractId ? contractRepository.getById(contractId) : undefined; if (!contract) return <section className="profile-not-found"><h1>Contract Not Found</h1><p>The requested contract could not be found.</p><Link className="button button-secondary" to="/marketing/contracts"><ArrowLeft size={15} />Back to Contracts</Link></section>; const customer = initialCustomers.find((item) => item.id === contract.customerId); const quotation = quotationRepository.getById(contract.quotationId); const request = serviceRequestRepository.findById(contract.serviceRequestId); return <section className="contract-placeholder-page"><Link className="contract-back-link" to={`/marketing/customers/${contract.customerId}?tab=contracts`}><ArrowLeft size={15} />Customer Contracts</Link><div className="contract-details-card"><span className="request-reference-icon"><FileSignature size={22} /></span><div><ContractStatusBadge status={getEffectiveContractStatus(contract)} /><h1>{contract.contractNumber}</h1><p>{contract.title}</p><SignatureStatusBadge status={contract.signatureStatus} /></div><dl><div><dt>Customer</dt><dd>{customer?.companyName ?? contract.customerId}</dd></div><div><dt>Related Quotation</dt><dd>{quotation?.quotationNumber ?? contract.quotationId}</dd></div><div><dt>Related Request</dt><dd>{request?.referenceNumber ?? contract.serviceRequestId}</dd></div><div><dt>Service and Vessel</dt><dd>{contract.serviceType} · {contract.vesselName}</dd></div><div><dt>Effective Period</dt><dd>{new Date(contract.effectiveDate).toLocaleDateString('en-PH')} – {new Date(contract.expirationDate).toLocaleDateString('en-PH')}</dd></div><div><dt>Contract Value</dt><dd>{formatCurrency(contract.contractValue)}</dd></div></dl></div><p className="contract-placeholder-note">Contract details will be implemented next.</p></section> }
