import { AlertTriangle, ArrowLeft, CalendarClock, Check, CheckCircle2, ChevronRight, Circle, ClipboardCheck, ExternalLink, FileCheck2, FileText, FolderOpen, History, LockKeyhole, MoreHorizontal, Plus, ReceiptText, Search, Send, Ship, UserRound } from 'lucide-react'
import { useDeferredValue, useState, type KeyboardEvent, type ReactNode } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ApprovalStatusBadge, QuotationStatusBadge } from '../../components/quotations/QuotationBadges'
import { EditQuotationModal } from '../../components/quotations/EditQuotationModal'
import { CreateRevisionDialog, RecordCustomerResponseDialog, SendQuotationDialog, SubmitQuotationDialog } from '../../components/customers/quotations/QuotationDialogs'
import { initialCustomers } from '../../data/customerMockData'
import { appointmentRepository } from '../../repositories/appointmentRepository'
import { contractRepository } from '../../repositories/contractRepository'
import { contractRequestRepository } from '../../repositories/contractRequestRepository'
import { customerActivityRepository } from '../../repositories/customerActivityRepository'
import { customerContactRepository } from '../../repositories/customerContactRepository'
import { customerDocumentRepository } from '../../repositories/customerDocumentRepository'
import { quotationRepository } from '../../repositories/quotationRepository'
import { serviceRequestRepository } from '../../repositories/serviceRequestRepository'
import { PROTOTYPE_ACTIVITY_ACTOR, type CustomerActivity } from '../../types/customerActivity'
import type { Quotation, QuotationResponse } from '../../types/quotation'
import { formatCurrency } from '../../utils/formatCurrency'
import { calculateQuotationTotals, getQuotationLineItems } from '../../utils/quotationPricing'
import { getQuotationValidity } from '../../utils/quotationValidity'
import { getAvailableQuotationActions, getInternalApprovalStatus, getQuotationDisplayStatus, type QuotationAction } from '../../utils/quotationWorkflow'

type Tab = 'overview' | 'pricing' | 'approvals' | 'documents' | 'activity'
type Dialog = 'edit' | 'submit' | 'send' | 'response' | 'revision' | null
type Confirm = { kind: 'delete' | 'withdraw' | 'resend' | 'extend' | 'contract' | 'response'; response?: QuotationResponse } | null
const date = new Intl.DateTimeFormat('en-PH', { month: 'short', day: 'numeric', year: 'numeric' })
const dateTime = new Intl.DateTimeFormat('en-PH', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' })
const displayDate = (value?: string) => value ? date.format(new Date(value)) : 'Not recorded'
const displayDateTime = (value?: string) => value ? dateTime.format(new Date(value)) : 'Not recorded'
const display = (value?: string | number) => value === undefined || value === '' ? 'Not provided' : String(value)
const initials = (name: string) => name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase()

function Card({ title, icon, children, action }: { title: string; icon: ReactNode; children: ReactNode; action?: ReactNode }) { return <section className="quotation-detail-card"><header><span>{icon}</span><h2>{title}</h2>{action}</header><div className="quotation-detail-card-body">{children}</div></section> }
function Grid({ items }: { items: { label: string; value: ReactNode }[] }) { return <dl className="quotation-detail-grid">{items.map((item) => <div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl> }

export function QuotationDetailsPlaceholder({ onNotify = () => undefined }: { onNotify?: (message: string) => void }) {
  const { quotationId } = useParams(); const navigate = useNavigate()
  const [quotation, setQuotation] = useState<Quotation | undefined>(() => quotationId ? quotationRepository.getById(quotationId) : undefined)
  const [tab, setTab] = useState<Tab>('overview'); const [dialog, setDialog] = useState<Dialog>(null); const [confirm, setConfirm] = useState<Confirm>(null); const [activityFilter, setActivityFilter] = useState('All'); const [documentSearch, setDocumentSearch] = useState(''); const deferredDocumentSearch = useDeferredValue(documentSearch.toLowerCase()); const [documentType, setDocumentType] = useState(''); const [note, setNote] = useState('')
  if (!quotation) return <main className="quotation-details-not-found"><ReceiptText size={34} /><h1>Quotation not found</h1><p>The requested quotation may have been removed or is unavailable.</p><div><Link className="button button-secondary" to="/marketing/quotations"><ArrowLeft size={15} />Back to Quotations</Link><Link className="button button-primary" to="/marketing/quotations">View All Quotations</Link></div></main>
  const customer = initialCustomers.find((item) => item.id === quotation.customerId); const request = serviceRequestRepository.findById(quotation.serviceRequestId); const contacts = customerContactRepository.getByCustomer(quotation.customerId); const contact = contacts.find((item) => item.id === quotation.contactId) ?? contacts.find((item) => item.isPrimary); const approvers = contacts.filter((item) => item.status === 'Active' && item.authorizations.canApproveQuotations)
  const status = getQuotationDisplayStatus(quotation); const approval = getInternalApprovalStatus(quotation); const validity = getQuotationValidity(quotation); const lineItems = getQuotationLineItems(quotation); const totals = calculateQuotationTotals(lineItems, quotation.discountAmount, quotation.additionalCharges)
  const contractRequest = contractRequestRepository.getByQuotationId(quotation.id); const contract = contractRepository.getByQuotationId(quotation.id); const appointments = appointmentRepository.getByCustomerId(quotation.customerId).filter((item) => item.relatedRecord?.type === 'Quotation' && item.relatedRecord.id === quotation.id)
  const documents = customerDocumentRepository.getByCustomerId(quotation.customerId).filter((item) => item.linkedRecords.some((record) => record.type === 'Quotation' && record.id === quotation.id)); const documentTypes = [...new Set(documents.map((item) => item.documentType))]; const filteredDocuments = documents.filter((item) => (!deferredDocumentSearch || [item.title, item.description, item.documentType].join(' ').toLowerCase().includes(deferredDocumentSearch)) && (!documentType || item.documentType === documentType))
  const family = quotationRepository.getAll().filter((item) => item.originalQuotationId === quotation.originalQuotationId).sort((a, b) => a.revisionNumber - b.revisionNumber); const familyIds = new Set(family.map((item) => item.id)); const allActivities = customerActivityRepository.getByCustomerId(quotation.customerId).filter((item) => item.relatedRecord?.type === 'Quotation' && familyIds.has(item.relatedRecord.id)); const activities = allActivities.filter((item) => activityFilter === 'All' || (activityFilter === 'Customer' ? item.actor.type === 'Customer' : activityFilter === 'System' ? item.actor.type === 'System' : item.actor.department === activityFilter))
  const refresh = (id = quotation.id) => setQuotation(quotationRepository.getById(id)); const notifyRefresh = (message: string) => { refresh(); onNotify(message) }
  const saveDraft = (changes: Partial<Quotation>) => { if (quotationRepository.updateDraft(quotation.id, changes)) notifyRefresh('Quotation draft updated.'); else onNotify('Only drafts may be edited.'); setDialog(null) }
  const recordResponse = (response: QuotationResponse) => { if (response.type === 'Customer Approved' || response.type === 'Rejected') { setConfirm({ kind: 'response', response }); setDialog(null); return } quotationRepository.recordCustomerResponse(quotation.id, response); notifyRefresh(response.type === 'Requested Revision' ? 'Customer changes requested.' : 'Pending customer decision recorded.'); setDialog(null) }
  const doConfirm = () => { if (!confirm) return; if (confirm.kind === 'delete') { quotationRepository.deleteDraft(quotation.id); navigate('/marketing/quotations'); return } if (confirm.kind === 'withdraw') quotationRepository.withdrawApprovalRequest(quotation.id); if (confirm.kind === 'resend') quotationRepository.update(quotation.id, { sentAt: new Date().toISOString() }); if (confirm.kind === 'extend') { const next = new Date(); next.setDate(next.getDate() + 30); quotationRepository.extendValidity(quotation.id, next.toISOString().slice(0, 10)) } if (confirm.kind === 'response' && confirm.response) quotationRepository.recordCustomerResponse(quotation.id, confirm.response); if (confirm.kind === 'contract') { const created = quotationRepository.requestContractPreparation(quotation.id); setConfirm(null); notifyRefresh(created ? `${created.referenceNumber} created for Document Control.` : 'An active contract request already exists or this quotation is not eligible.'); return } setConfirm(null); notifyRefresh('Quotation updated.') }
  const createRevision = (reason: string) => { const revision = quotationRepository.createRevision(quotation.id, reason); setDialog(null); if (revision) navigate(`/marketing/quotations/${revision.id}`) }
  const addNote = () => { if (!note.trim()) return; customerActivityRepository.append({ customerId: quotation.customerId, module: 'Quotations', action: 'Note Added', description: 'Internal quotation note added.', actor: PROTOTYPE_ACTIVITY_ACTOR, relatedRecord: { type: 'Quotation', id: quotation.id, referenceNumber: quotation.quotationNumber }, visibility: 'Internal', internalNote: note.trim(), systemGenerated: false, eventSource: 'quotationDetails' }); setNote(''); onNotify('Internal note added.') }
  const runAction = (action: QuotationAction) => { if (action === 'edit') setDialog('edit'); else if (action === 'submit') setDialog('submit'); else if (action === 'send') setDialog('send'); else if (action === 'response') setDialog('response'); else if (action === 'revision') setDialog('revision'); else if (action === 'duplicate') { const copy = quotationRepository.duplicate(quotation.id); if (copy) navigate(`/marketing/quotations/${copy.id}`) } else if (action === 'delete' || action === 'withdraw' || action === 'resend' || action === 'extend') setConfirm({ kind: action }); else if (action === 'contract') setConfirm({ kind: 'contract' }); else if (action === 'appointment') navigate(`/marketing/customers/${quotation.customerId}?tab=appointments&action=schedule`); else if (action === 'request') navigate(`/marketing/service-requests/${quotation.serviceRequestId}`); else if (action === 'print' || action === 'view') window.print(); else if (action === 'download') onNotify('PDF generation requires the production document service.'); else if (action === 'feedback') setTab('overview') }
  const primary: Partial<Record<typeof status, QuotationAction>> = { Draft: 'edit', 'For Approval': 'view', Approved: 'send', Sent: 'response', Viewed: 'response', 'Changes Requested': 'revision', Accepted: 'contract', Rejected: 'revision', Expired: 'revision' }; const primaryAction = status === 'Accepted' && contractRequest ? undefined : primary[status]; const secondary = getAvailableQuotationActions(quotation).filter((item) => item !== primaryAction && item !== 'view' && !(item === 'contract' && contractRequest))
  const primaryLabel: Record<string, string> = { edit: 'Edit Quotation', view: 'View Approval Progress', send: 'Send to Customer', response: 'Record Customer Response', revision: 'Create Revision', contract: 'Request Contract' }
  const actionLabel: Partial<Record<QuotationAction, string>> = { submit: 'Submit for Approval', duplicate: 'Duplicate', delete: 'Delete Draft', withdraw: 'Withdraw Approval Request', send: 'Send to Customer', download: 'Download PDF', print: 'Print', resend: 'Resend Quotation', response: 'View Customer Response', feedback: 'View Customer Feedback', revision: 'Create Revision', request: 'View Related Request', contract: 'Request Contract', appointment: 'Schedule Appointment', extend: 'Extend Validity' }
  const tabs: { id: Tab; label: string; count?: number }[] = [{ id: 'overview', label: 'Overview' }, { id: 'pricing', label: 'Pricing & Line Items', count: lineItems.length }, { id: 'approvals', label: 'Approvals' }, { id: 'documents', label: 'Documents', count: documents.length }, { id: 'activity', label: 'Activity Log', count: allActivities.length }]
  const onTabKey = (event: KeyboardEvent<HTMLButtonElement>, index: number) => { let next: number; if (event.key === 'ArrowRight') next = (index + 1) % tabs.length; else if (event.key === 'ArrowLeft') next = (index - 1 + tabs.length) % tabs.length; else if (event.key === 'Home') next = 0; else if (event.key === 'End') next = tabs.length - 1; else return; event.preventDefault(); setTab(tabs[next].id); document.getElementById(`quotation-tab-${tabs[next].id}`)?.focus() }
  const workflowLabels = ['Draft Created', 'Internal Review', 'Approved', 'Sent to Customer', 'Viewed', 'Customer Decision', 'Contract Requested']; const rank: Record<typeof status, number> = { Draft: 0, 'For Approval': 1, Approved: 2, Sent: 3, Viewed: 4, 'Changes Requested': 5, Accepted: 5, Rejected: 5, Expired: 3, Withdrawn: 1 }; const currentRank = rank[status]
  const validityMessage = status === 'Accepted' ? 'This quotation has been accepted by the customer.' : validity.classification === 'Expired' ? `This quotation expired on ${displayDate(quotation.validUntil)}.` : validity.classification === 'Expiring Soon' ? `This quotation ${validity.label.toLowerCase()}.` : `This quotation is valid until ${displayDate(quotation.validUntil)}.`
  return <main className="quotation-details-page"><Link className="quotation-details-back" to="/marketing/quotations"><ArrowLeft size={14} />Back to Quotations</Link><header className="quotation-details-header"><nav aria-label="Breadcrumb"><ol><li><Link to="/marketing/quotations">Quotations</Link></li><li><ChevronRight size={12} /></li><li aria-current="page">{quotation.quotationNumber}</li></ol></nav><div><div><span>{quotation.quotationNumber}</span><h1>Quotation Details</h1><p>Revision {quotation.revisionNumber} · {status}</p></div><div><QuotationStatusBadge status={status} /><ApprovalStatusBadge status={approval} /><small>Last updated {displayDateTime(quotation.updatedAt)}</small></div></div></header>
    <section className="quotation-details-summary"><div className="quotation-summary-document"><span><ReceiptText size={22} /></span><div><small>Commercial quotation</small><h2>{quotation.quotationNumber}</h2><b>Revision {quotation.revisionNumber}</b><p>{quotation.subject}</p><div><QuotationStatusBadge status={status} /><ApprovalStatusBadge status={approval} /></div></div></div><dl><div><dt>Customer</dt><dd><Link to={`/marketing/customers/${quotation.customerId}`}>{customer?.companyName ?? quotation.customerId}</Link></dd></div><div><dt>Primary contact</dt><dd>{contact ? `${contact.firstName} ${contact.lastName}` : 'Not provided'}</dd></div><div><dt>Related service request</dt><dd><Link to={`/marketing/service-requests/${quotation.serviceRequestId}`}>{request?.referenceNumber ?? quotation.serviceRequestId}</Link></dd></div><div><dt>Vessel</dt><dd>{request?.vessel.name ?? quotation.vesselName ?? 'Not provided'}</dd></div><div><dt>Service type</dt><dd>{request?.service.type ?? quotation.serviceType ?? 'Not provided'}</dd></div><div className="quotation-total-fact"><dt>Total quotation</dt><dd>{formatCurrency(quotation.totalAmount, quotation.currency)}</dd></div><div><dt>Validity</dt><dd>{displayDate(quotation.validFrom ?? quotation.createdAt)} – {displayDate(quotation.validUntil)}</dd></div><div><dt>Marketing representative</dt><dd>{quotation.assignedRepresentativeId ?? quotation.preparedBy}</dd></div></dl><div className="quotation-details-actions">{primaryAction && <button className="button button-primary" type="button" onClick={() => primaryAction === 'view' ? setTab('approvals') : runAction(primaryAction)}>{primaryLabel[primaryAction]}</button>}<button className="button button-secondary" type="button" onClick={() => window.print()}><FileText size={14} />Preview</button>{secondary.length > 0 && <details><summary><MoreHorizontal size={16} />More</summary><div>{secondary.map((action) => <button key={action} type="button" onClick={() => runAction(action)}>{actionLabel[action] ?? action}</button>)}</div></details>}</div></section>
    <aside className={`quotation-validity-alert ${status === 'Accepted' ? 'accepted' : validity.classification.toLowerCase().replaceAll(' ', '-')}`}><CalendarClock size={18} /><strong>{validityMessage}</strong></aside>
    <section className="quotation-workflow" aria-label="Quotation workflow"><ol>{workflowLabels.map((label, index) => { const completed = index < currentRank || (index === 6 && Boolean(contractRequest)); const current = index === currentRank && !(index === 5 && ['Rejected', 'Changes Requested'].includes(status)); const special = index === 5 && status === 'Rejected' ? 'rejected' : index === 5 && status === 'Changes Requested' ? 'revision' : index === 3 && status === 'Expired' ? 'expired' : ''; return <li key={label} className={completed ? 'completed' : current ? 'current' : special}><span>{completed ? <Check size={13} /> : special ? <AlertTriangle size={12} /> : <Circle size={10} />}</span><small>Step {index + 1}</small><strong>{label}</strong></li> })}</ol></section>
    <div className="quotation-details-tabs" role="tablist" aria-label="Quotation details sections">{tabs.map((item, index) => <button key={item.id} id={`quotation-tab-${item.id}`} role="tab" type="button" aria-selected={tab === item.id} tabIndex={tab === item.id ? 0 : -1} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)} onKeyDown={(event) => onTabKey(event, index)}>{item.label}{item.count !== undefined && <span>{item.count}</span>}</button>)}</div>
    {tab === 'overview' && <section className="quotation-overview" role="tabpanel"><div className="quotation-overview-main"><Card title="Customer information" icon={<UserRound size={16} />} action={<Link to={`/marketing/customers/${quotation.customerId}`}>View Customer</Link>}><Grid items={[{ label: 'Customer', value: customer?.companyName ?? quotation.customerId }, { label: 'Customer ID', value: quotation.customerId }, { label: 'Primary contact', value: contact ? `${contact.firstName} ${contact.lastName}` : customer?.primaryContact.name }, { label: 'Position', value: contact?.position ?? customer?.primaryContact.position }, { label: 'Email', value: contact?.email ?? customer?.primaryContact.email }, { label: 'Phone', value: contact?.primaryPhone ?? customer?.primaryContact.phone }, { label: 'Billing address', value: customer?.profileDetails ? `${customer.profileDetails.businessAddress}, ${customer.profileDetails.cityProvince}` : 'Not provided' }, { label: 'Preferred communication', value: contact?.preferredContactMethod ?? 'Not provided' }]} /><Link className="quotation-card-link" to={`/marketing/customers/${quotation.customerId}?tab=contacts`}>View Contacts <ExternalLink size={12} /></Link></Card>
      <Card title="Related service request" icon={<Ship size={16} />} action={<Link to={`/marketing/service-requests/${quotation.serviceRequestId}`}>View Request</Link>}><div className="operations-verified"><CheckCircle2 size={15} />Operational requirements verified by the Operations Department.</div><Grid items={[{ label: 'Reference', value: request?.referenceNumber ?? quotation.serviceRequestId }, { label: 'Service type', value: request?.service.type ?? quotation.serviceType }, { label: 'Requested date', value: displayDate(request?.schedule.requestedDate) }, { label: 'Vessel', value: request?.vessel.name ?? quotation.vesselName }, { label: 'Port / location', value: request?.schedule.portOrOperatingArea }, { label: 'Feasibility', value: request?.operationsReview?.status }, { label: 'Operations conditions', value: request?.operationsReview?.conditions ?? 'No special conditions' }, { label: 'Tugboat quantity', value: request?.service.tugboatsRequired }, { label: 'Estimated duration', value: request?.service.estimatedDuration }]} /></Card>
      <Card title="Quotation information" icon={<ReceiptText size={16} />}><Grid items={[{ label: 'Quotation', value: quotation.quotationNumber }, { label: 'Revision', value: quotation.revisionNumber }, { label: 'Original quotation', value: quotation.revisionNumber ? <Link to={`/marketing/quotations/${quotation.originalQuotationId}`}>View original</Link> : 'Original version' }, { label: 'Currency', value: quotation.currency }, { label: 'Issue date', value: displayDate(quotation.issuedAt) }, { label: 'Valid from', value: displayDate(quotation.validFrom ?? quotation.createdAt) }, { label: 'Valid until', value: displayDate(quotation.validUntil) }, { label: 'Assigned representative', value: quotation.assignedRepresentativeId ?? quotation.preparedBy }, { label: 'Prepared by', value: quotation.preparedBy }, { label: 'Purpose', value: quotation.subject }, { label: 'Customer-facing description', value: quotation.lineItemSummaries.join('; ') }]} />{family.length > 1 && <div className="revision-links"><strong>Revision history</strong>{family.map((item) => <Link key={item.id} className={item.id === quotation.id ? 'current' : ''} to={`/marketing/quotations/${item.id}`}>Revision {item.revisionNumber}</Link>)}</div>}</Card>
      <Card title="Commercial terms" icon={<FileCheck2 size={16} />}><Grid items={[{ label: 'Payment terms', value: quotation.paymentTerms ?? quotation.termsAndConditions }, { label: 'Billing schedule', value: display(quotation.billingSchedule) }, { label: 'Tax treatment', value: `${quotation.vatRate * 100}% VAT` }, { label: 'Deposit requirement', value: display(quotation.depositRequirement) }, { label: 'Cancellation policy', value: display(quotation.cancellationPolicy) }, { label: 'Rate adjustment', value: display(quotation.rateAdjustmentCondition) }, { label: 'Quotation validity', value: `${quotation.validityDays} days` }, { label: 'Commercial notes', value: display(quotation.additionalCommercialNotes) }]} />{status !== 'Draft' && <div className="locked-notice"><LockKeyhole size={14} />Approved financial terms are read-only.</div>}</Card>
      <Card title="Scope of service" icon={<ClipboardCheck size={16} />}><div className="quotation-scope-columns"><div><h3>Included Services</h3><ul>{lineItems.map((item) => <li key={item.id}>{item.description}</li>)}</ul></div><div><h3>Exclusions</h3><p>{quotation.termsAndConditions?.includes('subject') ? quotation.termsAndConditions : 'Services not expressly listed are excluded.'}</p></div><div><h3>Customer Responsibilities</h3><p>Provide safe access, confirmed schedule, vessel particulars, and required port clearances.</p></div></div><Grid items={[{ label: 'Service location', value: request?.schedule.portOrOperatingArea }, { label: 'Tugboat requirements', value: request ? `${request.service.tugboatsRequired} · ${request.service.preferredTugClass ?? 'Class not specified'}` : 'Not provided' }, { label: 'Estimated duration', value: request?.service.estimatedDuration }, { label: 'Equipment / safety', value: request?.operations.safetyRequirements ?? request?.operations.specialTugRequirements }, { label: 'Mobilization', value: request?.operations.natureOfAssistance }, { label: 'Operational conditions', value: request?.operationsReview?.conditions ?? 'None recorded' }]} /></Card>
      <Card title="Customer response" icon={<CheckCircle2 size={16} />}>{quotation.response ? <Grid items={[{ label: 'Response', value: quotation.response.type }, { label: 'Response date', value: displayDate(quotation.response.responseDate) }, { label: 'Responding contact', value: contacts.find((item) => item.id === quotation.response?.contactId) ? `${contacts.find((item) => item.id === quotation.response?.contactId)?.firstName} ${contacts.find((item) => item.id === quotation.response?.contactId)?.lastName}` : quotation.response.contactId }, { label: 'Response method', value: contact?.preferredContactMethod ?? 'Not recorded' }, { label: 'Customer comments', value: display(quotation.response.customerNotes) }, { label: 'Rejection reason', value: display(quotation.response.rejectionReason) }, { label: 'Requested changes', value: display(quotation.response.internalNotes) }, { label: 'Accepted amount', value: status === 'Accepted' ? formatCurrency(quotation.totalAmount, quotation.currency) : 'Not accepted' }, { label: 'Accepted validity', value: status === 'Accepted' ? displayDate(quotation.validUntil) : 'Not accepted' }]} /> : <div className="quotation-card-empty">No customer response has been recorded.</div>}</Card></div>
      <aside className="quotation-overview-aside"><Card title="Assignment and ownership" icon={<UserRound size={16} />}><div className="quotation-owner"><span>{initials(quotation.assignedRepresentativeId ?? quotation.preparedBy)}</span><div><strong>{quotation.assignedRepresentativeId ?? quotation.preparedBy}</strong><small>Marketing representative</small></div></div><Grid items={[{ label: 'Prepared by', value: quotation.preparedBy }, { label: 'Created', value: displayDateTime(quotation.createdAt) }, { label: 'Last modified', value: displayDateTime(quotation.updatedAt) }, { label: 'Follow-up', value: 'Not scheduled' }]} /><div className="quotation-tags">{(quotation.tags ?? ['commercial', 'quotation']).map((item) => <span key={item}>{item}</span>)}</div></Card>
      <Card title="Quotation status" icon={<History size={16} />}><Grid items={[{ label: 'Quotation status', value: <QuotationStatusBadge status={status} /> }, { label: 'Internal approval', value: <ApprovalStatusBadge status={approval} /> }, { label: 'Customer response', value: quotation.response?.type ?? 'No response' }, { label: 'Current workflow step', value: workflowLabels[currentRank] }, { label: 'Days remaining', value: validity.label }]} /></Card>
      <Card title="Important dates" icon={<CalendarClock size={16} />}><ul className="quotation-date-list">{[{ label: 'Draft created', value: quotation.createdAt }, { label: 'Submitted for approval', value: quotation.submittedForInternalApprovalAt }, { label: 'Approved internally', value: quotation.approvedAt }, { label: 'Sent to customer', value: quotation.sentAt }, { label: 'Viewed by customer', value: quotation.viewedAt }, { label: 'Customer response', value: quotation.respondedAt }, { label: 'Accepted', value: quotation.acceptedAt }, { label: 'Expiration', value: quotation.validUntil }, { label: 'Contract request', value: contractRequest?.createdAt }].filter((item) => item.value).map((item) => <li key={item.label}><span>{item.label}</span><time>{displayDateTime(item.value)}</time></li>)}</ul></Card>
      <Card title="Related records" icon={<FolderOpen size={16} />}><div className="quotation-related-records"><Related label="Customer" reference={customer?.companyName ?? quotation.customerId} to={`/marketing/customers/${quotation.customerId}`} status={customer?.status} /><Related label="Service Request" reference={request?.referenceNumber ?? quotation.serviceRequestId} to={`/marketing/service-requests/${quotation.serviceRequestId}`} status={request?.status} /><Related label="Vessel" reference={request?.vessel.name ?? quotation.vesselName ?? 'Not provided'} /><Related label="Contract Request" reference={contractRequest?.referenceNumber} status={contractRequest?.status} /><Related label="Contract" reference={contract?.contractNumber} to={contract ? `/marketing/contracts/${contract.id}` : undefined} status={contract?.status} /><Related label="Appointment" reference={appointments[0]?.title} to={`/marketing/customers/${quotation.customerId}?tab=appointments`} status={appointments[0]?.status} /><Related label="Invoice" /></div></Card></aside></section>}
    {tab === 'pricing' && <section className="quotation-pricing-tab" role="tabpanel"><div className="pricing-lock-banner"><LockKeyhole size={16} /><div><strong>{status === 'Draft' ? 'Marketing-editable draft pricing' : 'Pricing is locked because this quotation is no longer a draft.'}</strong><p>{status === 'Draft' ? 'Operations quantities remain read-only. Finance-controlled rates are subject to approval.' : 'Create a revision to propose changes.'}</p></div>{status === 'Draft' && <button className="button button-primary" type="button" onClick={() => setDialog('edit')}>Edit Pricing</button>}</div><div className="quotation-line-items-scroll"><table className="quotation-line-items"><thead><tr><th>Item</th><th>Description</th><th>Quantity</th><th>Unit</th><th>Unit Rate</th><th>Duration</th><th>Discount</th><th>Tax</th><th>Line Total</th></tr></thead><tbody>{lineItems.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><span>{item.source} controlled</span></td><td>{item.description}</td><td>{item.quantity}</td><td>{item.unit}</td><td>{formatCurrency(item.unitRate, quotation.currency)}</td><td>{item.duration ? `${item.duration} ${item.durationUnit ?? ''}` : '—'}</td><td>{formatCurrency(item.discountAmount, quotation.currency)}</td><td>{item.taxRate * 100}%</td><td><strong>{formatCurrency(item.totalAmount, quotation.currency)}</strong></td></tr>)}</tbody></table></div><div className="quotation-pricing-bottom"><Card title="Pricing notes" icon={<FileText size={16} />}><Grid items={[{ label: 'Currency', value: quotation.currency }, { label: 'Rate basis', value: 'Per approved service scope' }, { label: 'Payment terms', value: quotation.paymentTerms ?? quotation.termsAndConditions }, { label: 'Deposit', value: display(quotation.depositRequirement) }, { label: 'Tax notes', value: `${quotation.vatRate * 100}% VAT applied after discounts` }, { label: 'Price adjustment', value: display(quotation.rateAdjustmentCondition) }, { label: 'Approved discount limit', value: '10% of subtotal' }]} /></Card><section className="quotation-totals"><h2>Pricing Summary</h2><dl><div><dt>Subtotal</dt><dd>{formatCurrency(totals.subtotal, quotation.currency)}</dd></div><div><dt>Line-item discounts</dt><dd>− {formatCurrency(totals.lineItemDiscounts, quotation.currency)}</dd></div><div><dt>Quotation discount</dt><dd>− {formatCurrency(totals.quotationDiscount, quotation.currency)}</dd></div><div><dt>Amount before tax</dt><dd>{formatCurrency(totals.amountBeforeTax, quotation.currency)}</dd></div><div><dt>Tax</dt><dd>{formatCurrency(totals.tax, quotation.currency)}</dd></div><div><dt>Additional charges</dt><dd>{formatCurrency(totals.additionalCharges, quotation.currency)}</dd></div><div className="grand-total"><dt>Grand total</dt><dd>{formatCurrency(totals.grandTotal, quotation.currency)}</dd></div></dl></section></div></section>}
    {tab === 'approvals' && <section className="quotation-approvals-tab" role="tabpanel"><div className="approval-cards"><ApprovalCard title="Operations verification" status={request?.operationsReview?.status ?? 'Not Submitted'} reviewer={request?.operationsReview?.reviewedBy} submitted={request?.operationsReview?.submittedAt} reviewed={request?.operationsReview?.reviewedAt} details={[`Requirements: ${request?.service.tugboatsRequired ?? '—'} tugboat(s), ${request?.service.preferredTugClass ?? 'class not specified'}`, `Conditions: ${request?.operationsReview?.conditions ?? 'None recorded'}`, `Notes: ${request?.operationsReview?.internalNotes ?? 'None shared'}`]} /><ApprovalCard title="Finance approval" status={approval} submitted={quotation.submittedForInternalApprovalAt} reviewed={quotation.approvedAt} details={[`Approved amount: ${approval === 'Approved' ? formatCurrency(quotation.totalAmount, quotation.currency) : 'Pending'}`, `Discount: ${formatCurrency(quotation.discountAmount ?? 0, quotation.currency)}`, `Tax verification: ${approval === 'Approved' ? 'Verified' : 'Pending verification'}`, `Payment terms: ${quotation.paymentTerms ?? quotation.termsAndConditions ?? 'Not submitted'}`]} />{(quotation.discountAmount ?? 0) > quotation.subtotal * .05 && <ApprovalCard title="Management approval" status={approval === 'Approved' ? 'Approved' : 'Pending'} submitted={quotation.submittedForInternalApprovalAt} details={['Reason: Exceptional discount above standard threshold', 'Notes: Awaiting management decision']} />}</div><Card title="Approval timeline" icon={<ClipboardCheck size={16} />}><ol className="approval-timeline"><li className="complete"><span><Check size={12} /></span><div><strong>Operations verification</strong><small>{displayDateTime(request?.operationsReview?.reviewedAt)}</small></div></li><li className={quotation.submittedForInternalApprovalAt ? 'complete' : ''}><span>{quotation.submittedForInternalApprovalAt ? <Check size={12} /> : <Circle size={10} />}</span><div><strong>Submitted for Finance approval</strong><small>{displayDateTime(quotation.submittedForInternalApprovalAt)}</small></div></li><li className={approval === 'Approved' ? 'complete' : ''}><span>{approval === 'Approved' ? <Check size={12} /> : <Circle size={10} />}</span><div><strong>Financial terms approved</strong><small>{approval === 'Approved' ? displayDateTime(quotation.approvedAt ?? quotation.updatedAt) : approval}</small></div></li></ol><div className="approval-marketing-actions">{status === 'Draft' && <button className="button button-primary" onClick={() => setDialog('submit')}>Submit for Approval</button>}{status === 'For Approval' && <button className="button button-secondary" onClick={() => setConfirm({ kind: 'withdraw' })}>Withdraw Approval Request</button>}<button className="button button-secondary" onClick={() => onNotify('Submitted approval information is displayed above.')}>View Submitted Information</button></div></Card></section>}
    {tab === 'documents' && <section className="quotation-documents-tab" role="tabpanel"><div className="quotation-documents-tools"><label><Search size={14} /><span className="sr-only">Search documents</span><input value={documentSearch} placeholder="Search quotation documents" onChange={(event) => setDocumentSearch(event.target.value)} /></label><select aria-label="Document type" value={documentType} onChange={(event) => setDocumentType(event.target.value)}><option value="">All document types</option>{documentTypes.map((item) => <option key={item}>{item}</option>)}</select><Link className="button button-primary" to={`/marketing/customers/${quotation.customerId}?tab=documents`}><Plus size={14} />Add Supporting Document</Link></div>{filteredDocuments.length ? <div className="quotation-documents-scroll"><table><thead><tr><th>Document name</th><th>Type</th><th>Revision</th><th>File size</th><th>Uploaded by</th><th>Upload date</th><th>Visibility</th><th>Actions</th></tr></thead><tbody>{filteredDocuments.map((document) => { const version = document.versions.find((item) => item.version === document.currentVersion) ?? document.versions.at(-1); return <tr key={document.id}><td><strong>{document.title}</strong><span>{version?.fileName}</span></td><td>{document.documentType}</td><td>v{document.currentVersion}</td><td>{version ? `${(version.sizeBytes / 1024).toFixed(1)} KB` : '—'}</td><td>{version?.uploadedBy ?? document.createdBy}</td><td>{displayDate(version?.uploadedAt ?? document.createdAt)}</td><td><span className="document-visibility">{document.visibility === 'Customer Visible' ? 'Shared with Customer' : 'Internal'}</span></td><td><button type="button" disabled title="Prototype metadata only">Preview</button><button type="button" disabled title="Prototype metadata only">Download</button></td></tr> })}</tbody></table></div> : <div className="quotation-card-empty"><FolderOpen size={28} /><strong>No quotation documents found</strong><p>Link supporting documents from the customer Documents tab.</p></div>}</section>}
    {tab === 'activity' && <section className="quotation-activity-tab" role="tabpanel"><div className="quotation-activity-tools"><div>{['All', 'Marketing', 'Operations', 'Finance', 'Management', 'Customer', 'System'].map((item) => <button key={item} className={activityFilter === item ? 'active' : ''} type="button" onClick={() => setActivityFilter(item)}>{item}</button>)}</div><form onSubmit={(event) => { event.preventDefault(); addNote() }}><input value={note} aria-label="Internal note" placeholder="Add an internal note" onChange={(event) => setNote(event.target.value)} /><button className="button button-primary" type="submit">Add Internal Note</button></form></div>{activities.length ? <ol className="quotation-activity-timeline">{activities.map((activity) => <Activity key={activity.id} activity={activity} />)}</ol> : <div className="quotation-card-empty"><History size={28} /><strong>No activities match this filter.</strong></div>}</section>}
    {dialog === 'edit' && <EditQuotationModal quotation={quotation} request={request} onClose={() => setDialog(null)} onSave={saveDraft} />}{dialog === 'submit' && <SubmitQuotationDialog quotation={quotation} onClose={() => setDialog(null)} onConfirm={() => { const updated = quotationRepository.submitForInternalApproval(quotation.id); setDialog(null); notifyRefresh(updated ? 'Quotation submitted for Finance approval.' : 'Complete pricing and terms before submitting.') }} />}{dialog === 'send' && customer && <SendQuotationDialog quotation={quotation} customer={customer} contacts={approvers} onClose={() => setDialog(null)} onConfirm={(contactId) => { quotationRepository.markAsSent(quotation.id, contactId); setDialog(null); notifyRefresh('Quotation sent to the customer.') }} />}{dialog === 'response' && <RecordCustomerResponseDialog contacts={approvers} onClose={() => setDialog(null)} onConfirm={recordResponse} />}{dialog === 'revision' && <CreateRevisionDialog onClose={() => setDialog(null)} onConfirm={createRevision} />}
    {confirm && <div className="modal-backdrop"><section className="quotation-confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="quotation-detail-confirm"><h2 id="quotation-detail-confirm">Confirm {confirm.kind}</h2><p>This action updates {quotation.quotationNumber} and its audit history. Continue?</p><div><button className="button button-secondary" type="button" onClick={() => setConfirm(null)}>Cancel</button><button className="button button-primary" type="button" onClick={doConfirm}>Confirm</button></div></section></div>}
  </main>
}

function Related({ label, reference, status, to }: { label: string; reference?: string; status?: string; to?: string }) { return <div><span><FileText size={14} /></span><div><small>{label}</small><strong>{reference ?? 'Not created'}</strong>{status && <em>{status}</em>}</div>{to && <Link to={to}>View</Link>}</div> }
function ApprovalCard({ title, status, reviewer, submitted, reviewed, details }: { title: string; status: string; reviewer?: string; submitted?: string; reviewed?: string; details: string[] }) { return <article className="quotation-approval-card"><header><div><small>Department review</small><h2>{title}</h2></div><strong>{status}</strong></header><dl><div><dt>Reviewer</dt><dd>{reviewer ?? 'Not assigned'}</dd></div><div><dt>Submitted</dt><dd>{displayDateTime(submitted)}</dd></div><div><dt>Decision</dt><dd>{displayDateTime(reviewed)}</dd></div></dl><ul>{details.map((item) => <li key={item}>{item}</li>)}</ul></article> }
function Activity({ activity }: { activity: CustomerActivity }) { return <li><span>{activity.action === 'Approved' ? <CheckCircle2 size={15} /> : activity.action === 'Submitted' ? <Send size={15} /> : <History size={15} />}</span><article><header><div><strong>{activity.description}</strong><p>{activity.action} · {activity.module}</p></div><time>{displayDateTime(activity.occurredAt)}</time></header><footer><span>{activity.actor.name} · {activity.actor.department ?? activity.actor.type}</span>{activity.relatedRecord && <Link to={`/marketing/quotations/${activity.relatedRecord.id}`}>{activity.relatedRecord.referenceNumber}</Link>}</footer>{activity.internalNote && <blockquote>Internal — not visible to the customer<br />{activity.internalNote}</blockquote>}</article></li> }
