import { Calculator, LockKeyhole } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import type { Quotation } from '../../types/quotation'
import type { ServiceRequest } from '../../types/serviceRequest'
import { formatCurrency } from '../../utils/formatCurrency'

export function EditQuotationModal({ quotation, request, onClose, onSave }: { quotation: Quotation; request?: ServiceRequest; onClose: () => void; onSave: (changes: Partial<Quotation>) => void }) {
  const ref = useRef<HTMLElement>(null)
  const [subject, setSubject] = useState(quotation.subject); const [description, setDescription] = useState(quotation.lineItemSummaries.join('\n')); const [subtotal, setSubtotal] = useState(String(quotation.subtotal)); const [discount, setDiscount] = useState(String(quotation.discountAmount ?? 0)); const [validUntil, setValidUntil] = useState(quotation.validUntil?.slice(0, 10) ?? ''); const [terms, setTerms] = useState(quotation.termsAndConditions ?? ''); const [error, setError] = useState('')
  const subtotalNumber = Number(subtotal) || 0; const discountNumber = Number(discount) || 0; const taxable = Math.max(0, subtotalNumber - discountNumber); const tax = taxable * quotation.vatRate; const total = taxable + tax
  useEffect(() => { ref.current?.querySelector<HTMLInputElement>('input')?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key) }, [onClose])
  const save = () => { if (!subject.trim() || !description.trim() || subtotalNumber <= 0 || discountNumber < 0 || discountNumber > subtotalNumber * .1 || !validUntil || !terms.trim()) { setError('Complete all required fields. Discounts cannot exceed 10% of subtotal.'); return } onSave({ subject: subject.trim(), lineItemSummaries: description.split('\n').map((item) => item.trim()).filter(Boolean), subtotal: subtotalNumber, discountAmount: discountNumber, vatAmount: tax, taxAmount: tax, totalAmount: total, validUntil: new Date(`${validUntil}T23:59:59.999Z`).toISOString(), termsAndConditions: terms.trim() }) }
  return <div className="modal-backdrop"><section ref={ref} className="edit-quotation-modal" role="dialog" aria-modal="true" aria-labelledby="edit-quotation-title"><header><span><Calculator size={20} /></span><div><small>Marketing draft</small><h2 id="edit-quotation-title">Edit {quotation.quotationNumber}</h2></div></header><div className="edit-quotation-body"><div className="operations-lock-note"><LockKeyhole size={15} /><span><strong>Operations-approved scope is locked</strong>{request ? `${request.service.tugboatsRequired} tugboat(s) · ${request.service.preferredTugClass ?? 'Class not specified'} · ${request.operationsReview?.conditions ?? 'No conditions'}` : 'Operational scope is maintained on the related request.'}</span></div><div className="edit-quotation-grid"><label className="wide"><span>Customer-facing subject *</span><input value={subject} onChange={(event) => setSubject(event.target.value)} /></label><label className="wide"><span>Customer-facing descriptions *</span><textarea rows={3} value={description} onChange={(event) => setDescription(event.target.value)} /></label><label><span>Subtotal *</span><input type="number" min="0" step="100" value={subtotal} onChange={(event) => setSubtotal(event.target.value)} /></label><label><span>Authorized discount</span><input type="number" min="0" max={subtotalNumber * .1} step="100" value={discount} onChange={(event) => setDiscount(event.target.value)} /></label><label><span>Tax ({quotation.vatRate * 100}%)</span><input value={formatCurrency(tax, quotation.currency)} readOnly /></label><label><span>Total</span><input value={formatCurrency(total, quotation.currency)} readOnly /></label><label><span>Valid until *</span><input type="date" value={validUntil} onChange={(event) => setValidUntil(event.target.value)} /></label><label className="wide"><span>Payment terms and conditions *</span><textarea rows={3} value={terms} onChange={(event) => setTerms(event.target.value)} /></label></div>{error && <p className="dialog-error" role="alert">{error}</p>}</div><footer><button className="button button-secondary" type="button" onClick={onClose}>Cancel</button><button className="button button-primary" type="button" onClick={save}>Save Draft</button></footer></section></div>
}
