import { UserRoundPlus, X } from 'lucide-react'
import { useEffect, useRef, useState, type FormEvent } from 'react'
import type { ContactStatus, ContactType, CustomerContact, CustomerContactInput, PreferredContactMethod } from '../../../types/customerContact'

const contactTypes: ContactType[] = ['Commercial', 'Operations', 'Billing', 'Emergency', 'Authorized Signatory', 'Other']
const defaultInput: CustomerContactInput = { firstName: '', middleName: '', lastName: '', position: '', department: '', contactTypes: [], email: '', primaryPhone: '', secondaryPhone: '', preferredContactMethod: 'Email', availableDays: [], preferredContactStartTime: '', preferredContactEndTime: '', timeZone: 'Asia/Manila', isPrimary: false, status: 'Active', authorizations: { canApproveQuotations: false, canSignContracts: false, canCoordinateOperations: false }, internalNotes: '', lastContactedAt: '' }
type Errors = Partial<Record<'firstName' | 'lastName' | 'position' | 'contactTypes' | 'email' | 'primaryPhone' | 'preferredContactMethod' | 'preferredContactEndTime', string>>

interface Props { contact?: CustomerContact; existingContacts: CustomerContact[]; onClose: () => void; onSave: (input: CustomerContactInput) => void }
export function ContactFormModal({ contact, existingContacts, onClose, onSave }: Props) {
  const [form, setForm] = useState<CustomerContactInput>(() => contact ? { ...contact } : defaultInput)
  const [errors, setErrors] = useState<Errors>({})
  const [message, setMessage] = useState('')
  const dialogRef = useRef<HTMLDivElement>(null)
  const firstRef = useRef<HTMLInputElement>(null)
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; firstRef.current?.focus(); const keydown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key !== 'Tab' || !dialogRef.current) return; const focusable = [...dialogRef.current.querySelectorAll<HTMLElement>('button,input,select,textarea')]; const first = focusable[0]; const last = focusable.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus() } }; document.addEventListener('keydown', keydown); return () => { document.body.style.overflow = overflow; document.removeEventListener('keydown', keydown); previous?.focus() } }, [onClose])
  const update = <K extends keyof CustomerContactInput>(key: K, value: CustomerContactInput[K]) => { setForm((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: undefined })) }
  const submit = (event: FormEvent) => {
    event.preventDefault(); const next: Errors = {}
    if (!form.firstName.trim()) next.firstName = 'First name is required.'
    if (!form.lastName.trim()) next.lastName = 'Last name is required.'
    if (!form.position.trim()) next.position = 'Position is required.'
    if (!form.contactTypes.length) next.contactTypes = 'Select at least one contact type.'
    if (!form.email.trim()) next.email = 'Email is required.'
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) next.email = 'Enter a valid email address.'
    else if (existingContacts.some((item) => item.id !== contact?.id && item.email.toLowerCase() === form.email.toLowerCase())) next.email = 'Email must be unique for this customer.'
    if (!form.primaryPhone.trim()) next.primaryPhone = 'Primary phone is required.'
    if (!form.preferredContactMethod) next.preferredContactMethod = 'Preferred contact method is required.'
    if (form.preferredContactStartTime && form.preferredContactEndTime && form.preferredContactEndTime < form.preferredContactStartTime) next.preferredContactEndTime = 'End time cannot occur before start time.'
    setErrors(next); if (Object.keys(next).length) { setMessage('Please review the highlighted fields.'); window.setTimeout(() => document.getElementById(`contact-${Object.keys(next)[0]}`)?.focus(), 0); return }
    onSave(form)
  }
  const field = (key: 'firstName' | 'middleName' | 'lastName' | 'position' | 'department' | 'email' | 'primaryPhone' | 'secondaryPhone' | 'timeZone', label: string, required = false, type = 'text', ref?: typeof firstRef) => <label className="form-field"><span>{label}{required && <em> *</em>}</span><input id={`contact-${key}`} ref={ref} type={type} value={String(form[key] ?? '')} aria-invalid={Boolean(errors[key as keyof Errors])} aria-describedby={errors[key as keyof Errors] ? `contact-${key}-error` : undefined} onChange={(event) => update(key, event.target.value)} />{errors[key as keyof Errors] && <small id={`contact-${key}-error`}>{errors[key as keyof Errors]}</small>}</label>
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><div ref={dialogRef} className="customer-modal contact-form-modal" role="dialog" aria-modal="true" aria-labelledby="contact-form-title"><header className="modal-header contact-modal-header"><span className="contact-modal-icon"><UserRoundPlus size={20} /></span><div><h2 id="contact-form-title">{contact ? 'Edit Contact' : 'Add Contact'}</h2><p>{contact ? 'Update customer contact information.' : 'Add a person associated with this customer.'}</p></div><button type="button" aria-label="Close contact form" onClick={onClose}><X size={18} /></button></header><form onSubmit={submit} noValidate><div className="modal-body contact-modal-body">{message && <div className="request-form-alert" role="alert">{message}</div>}
    <fieldset className="contact-form-section contact-personal-section"><legend>Personal Information</legend><div className="form-grid contact-personal-grid">{field('firstName', 'First Name', true, 'text', firstRef)}{field('middleName', 'Middle Name')}{field('lastName', 'Last Name', true)}{field('position', 'Position', true)}{field('department', 'Department')}<div id="contact-contactTypes" className="form-field form-field-wide" tabIndex={-1}><span>Contact Types <em>*</em></span><div className="contact-type-options">{contactTypes.map((type) => <label key={type}><input type="checkbox" checked={form.contactTypes.includes(type)} onChange={(event) => update('contactTypes', event.target.checked ? [...form.contactTypes, type] : form.contactTypes.filter((item) => item !== type))} />{type}</label>)}</div>{errors.contactTypes && <small id="contact-contactTypes-error">{errors.contactTypes}</small>}</div></div></fieldset>
    <fieldset className="contact-form-section"><legend>Contact Information</legend><div className="form-grid">{field('email', 'Email Address', true, 'email')}{field('primaryPhone', 'Primary Phone', true, 'tel')}{field('secondaryPhone', 'Secondary Phone', false, 'tel')}<label className="form-field"><span>Preferred Contact Method <em>*</em></span><select id="contact-preferredContactMethod" value={form.preferredContactMethod} onChange={(event) => update('preferredContactMethod', event.target.value as PreferredContactMethod)}>{['Email', 'Phone', 'SMS'].map((method) => <option key={method}>{method}</option>)}</select></label></div></fieldset>
    <fieldset className="contact-form-section"><legend>Availability</legend><div className="form-grid contact-availability-grid"><label className="form-field form-field-wide"><span>Available Days</span><div className="contact-day-options">{['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map((day) => <label key={day}><input type="checkbox" checked={form.availableDays?.includes(day)} onChange={(event) => update('availableDays', event.target.checked ? [...(form.availableDays ?? []), day] : form.availableDays?.filter((item) => item !== day))} />{day.slice(0, 3)}</label>)}</div></label><label className="form-field"><span>Preferred Contact Start Time</span><input type="time" value={form.preferredContactStartTime} onChange={(event) => update('preferredContactStartTime', event.target.value)} /></label><label className="form-field"><span>Preferred Contact End Time</span><input id="contact-preferredContactEndTime" type="time" value={form.preferredContactEndTime} aria-invalid={Boolean(errors.preferredContactEndTime)} onChange={(event) => update('preferredContactEndTime', event.target.value)} />{errors.preferredContactEndTime && <small>{errors.preferredContactEndTime}</small>}</label>{field('timeZone', 'Time Zone')}</div></fieldset>
    <fieldset className="contact-form-section"><legend>Authorizations</legend><div className="authorization-options">{([['canApproveQuotations', 'Authorized to Approve Quotations'], ['canSignContracts', 'Authorized to Sign Contracts'], ['canCoordinateOperations', 'Authorized to Coordinate Operations']] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={form.authorizations[key]} onChange={(event) => update('authorizations', { ...form.authorizations, [key]: event.target.checked })} />{label}</label>)}</div></fieldset>
    <fieldset className="contact-form-section"><legend>Additional Information</legend><div className="form-grid"><label className="form-field"><span>Status</span><select value={form.status} onChange={(event) => update('status', event.target.value as ContactStatus)}><option>Active</option><option>Inactive</option></select></label><label className="contact-primary-checkbox"><input type="checkbox" checked={form.isPrimary} onChange={(event) => update('isPrimary', event.target.checked)} />Set as Primary Contact</label><label className="form-field form-field-wide"><span>Internal Notes</span><textarea rows={3} value={form.internalNotes} onChange={(event) => update('internalNotes', event.target.value)} /><small>Internal notes are visible only to SEDAR personnel.</small></label></div></fieldset>
  </div><footer className="modal-footer contact-modal-footer"><button className="button button-secondary" type="button" onClick={onClose}>Cancel</button><button className="button button-primary" type="submit">{contact ? 'Save Changes' : 'Add Contact'}</button></footer></form></div></div>
}
