import { ClipboardPen, Download, Eye, FilePenLine, FilePlus2, MoreHorizontal, PenLine, RefreshCw, Send, XCircle } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import type { Contract, ContractStatus } from '../../../types/contract'
import type { ContractValidityClassification } from '../../../types/contract'

interface Props { contract: Contract; status: ContractStatus; validity: ContractValidityClassification; open: boolean; onOpenChange: (open: boolean) => void; onView: () => void; onEdit: () => void; onSubmit: () => void; onSend: () => void; onSignature: () => void; onDownload: () => void; onAmend: () => void; onRenew: () => void; onTerminate: () => void }
export function ContractActionsMenu({ contract, status, validity, open, onOpenChange, onView, onEdit, onSubmit, onSend, onSignature, onDownload, onAmend, onRenew, onTerminate }: Props) {
  const triggerRef = useRef<HTMLButtonElement>(null); const menuRef = useRef<HTMLDivElement>(null); const [position, setPosition] = useState({ top: 0, right: 8 })
  const canRenew = status === 'Expired' || (status === 'Active' && validity === 'Expiring Soon')
  const actionCount = 2 + (status === 'Draft' ? 2 : 0) + (status === 'Ready for Signature' ? 1 : 0) + (['Ready for Signature', 'Awaiting Signatures'].includes(status) ? 1 : 0) + (status === 'Active' ? 2 : 0) + (canRenew ? 1 : 0)
  useEffect(() => { if (!open) return; const outside = (event: PointerEvent) => { const target = event.target as Node; if (!triggerRef.current?.contains(target) && !menuRef.current?.contains(target)) onOpenChange(false) }; const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') { onOpenChange(false); triggerRef.current?.focus() } }; const reposition = () => { if (!triggerRef.current) return; const rect = triggerRef.current.getBoundingClientRect(); const menuHeight = actionCount * 34 + 12; setPosition({ top: rect.bottom + menuHeight > innerHeight - 8 ? Math.max(8, rect.top - menuHeight - 4) : rect.bottom + 4, right: Math.max(8, innerWidth - rect.right) }) }; document.addEventListener('pointerdown', outside); document.addEventListener('keydown', escape); window.addEventListener('resize', reposition); window.addEventListener('scroll', reposition, true); return () => { document.removeEventListener('pointerdown', outside); document.removeEventListener('keydown', escape); window.removeEventListener('resize', reposition); window.removeEventListener('scroll', reposition, true) } }, [open, onOpenChange, actionCount])
  const toggle = () => { if (!open && triggerRef.current) { const rect = triggerRef.current.getBoundingClientRect(); const menuHeight = actionCount * 34 + 12; setPosition({ top: rect.bottom + menuHeight > innerHeight - 8 ? Math.max(8, rect.top - menuHeight - 4) : rect.bottom + 4, right: Math.max(8, innerWidth - rect.right) }) } onOpenChange(!open) }
  const action = (callback: () => void) => () => { onOpenChange(false); callback() }
  return <><button ref={triggerRef} className="customer-menu-trigger" type="button" aria-label={`Actions for ${contract.contractNumber}`} aria-haspopup="menu" aria-expanded={open} onClick={toggle}><MoreHorizontal size={18} /></button>{open && createPortal(<div ref={menuRef} className="customer-action-menu contract-action-menu" role="menu" style={position}><button role="menuitem" type="button" onClick={action(onView)}><Eye size={14} />View Contract</button>{status === 'Draft' && <><button role="menuitem" type="button" onClick={action(onEdit)}><FilePenLine size={14} />Edit Contract</button><button role="menuitem" type="button" onClick={action(onSubmit)}><ClipboardPen size={14} />Submit for Internal Review</button></>}{status === 'Ready for Signature' && <button role="menuitem" type="button" onClick={action(onSend)}><Send size={14} />Send for Signature</button>}{['Ready for Signature', 'Awaiting Signatures'].includes(status) && <button role="menuitem" type="button" onClick={action(onSignature)}><PenLine size={14} />Record Signature</button>}<button role="menuitem" type="button" onClick={action(onDownload)}><Download size={14} />Download Contract</button>{status === 'Active' && <button role="menuitem" type="button" onClick={action(onAmend)}><FilePlus2 size={14} />Create Amendment</button>}{canRenew && <button role="menuitem" type="button" onClick={action(onRenew)}><RefreshCw size={14} />Renew Contract</button>}{status === 'Active' && <button className="menu-danger" role="menuitem" type="button" onClick={action(onTerminate)}><XCircle size={14} />Request Termination</button>}</div>, document.body)}</>
}
